print("sam's hospital")
print("Appointment submission")
print("Please provide the patient's details before proceeding")
print("patient detail:-")
name = str(input("enter your name: "))
dob = str(input("enter birth date: "))
number = str(input("enter your phone number: "))
email = str(input("enter your email: "))
print("welcome,", name, "!", "You may now fill in the contact information")
print("contact details:-")
Address1 = str(input("enter your Address 1: "))
Address2 = str(input("enter your Address 2: "))
Address3 = str(input("enter your Address 3: "))
area = str(input("enter your area: "))
state = str(input("enter your state: "))
city = str(input("enter your city: "))
zipcode = str(input("enter your zipcode: "))
print("appointment needed details:-")
problem = str(input('''Describe the problem you're experiencing: '''))
need1 = str(input("Day Preferred: "))
need2 = str(input("Secondary Day Preferred: "))
print("Thank you for choosing us.", name, '''We will investigate your concerns and contact you as soon as possible 
about your appointment''')
